#!/usr/bin/python
import sys
# Enter your code here. Read input from STDIN. Print output to STDOUT
t = int(raw_input())

for i in range(t):
    num = int(raw_input())
    nthree = 0
    nfive = 0
    flag = True
    while num > 0:
        print num
        if num % 3 == 0:
            nfive += 3
            num -= 3
        elif num % 5 == 0:
            nthree += 5
            num -= 5
        elif num > 5:
            nfive += 3
            num -= 3
        else:
            flag = False
            break
    if flag:
        for i in range(nfive):
            sys.stdout.write("5")
        for j in range(nthree):
            sys.stdout.write("3")
    else:
        print "-1"
