#!/usr/bin/python

def zero(matrix):
    row = 0
    col = 0

    
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] == 0:
                row |= 1<<i
                col |= 1<<j
    #i = j = 0
    
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            #print "i = {0}, j = {1}".format(i,j)
            if (row&(1<<i)) or (col&(1<<j)):
                # print "in"
                matrix[i][j] = 0
    #print "row: ", row
    #print "column: ", col

if __name__ == "__main__":
    m = [[1,2,0,4,5],[1,3,4,5,6],[1,2,3,4,5]]
    zero(m)

    for x in m:
        for y in x:
            print y,
        print 

