#!usr/bin/python
 class ListNode(object):
     def __init__(self, x):
         self.val = x
         self.next = None

class Solution(object):
    def insertionSortList(self, head):
        """
        :type head: ListNode
        :rtype: ListNode
        """
        if head == None or head.next == None:
            return head
        node = head.next
        
        while node != None:
            temp = head
            #print "hello"
            while temp != node:
                if temp.val >= node.val :
                    p = node.val
                    while temp != node.next :
                        t = temp.val
                        temp.val = p
                        p = t
                        temp = temp.next
                        
                    break
                temp = temp.next
            node = node.next
            
        return head
